#!/bin/bash

#Help Menu
if [ $# -eq 0 ] || [[ $* == *-h* ]]
  then
    echo "Useage: ./mktap file.asm [output name]"
    echo ""
    echo "Options:"
    echo "  -h   help"
    echo ""
    exit
fi

#Check if input exists
if [ ! -e $1 ]
  then
    echo "Error: input asm file does not exist"
    exit
fi

#Strip the file of its extension to ensure clean output name
FILENAME=""
if [ $# -eq 1 ] 
  then
    FILENAME=${1%.*}
elif [ $# -eq 2 ]
  then
    FILENAME=${2%.*}
else
  echo "Error: too many args"
  exit
fi

#Compile the z80 code
z80asm $1 -o $FILENAME.bin

#If successfully compiled, create the output and clean up
if [ -e $FILENAME.bin ]
  then
    bin2tap -b -hp $FILENAME.bin -o $FILENAME.tap
    printf "The binary size is: %s\n" `ls -lh $FILENAME.bin | awk '{print $5}'` 
    rm $FILENAME.bin
fi

